### ISSUE TITLE
gem version goes next line of the add gems

### ISSUE THREAD

**Issue by selvamani-subramani** [stompesi/gemput#2]
When I run `gemput sync`, its added the version in Gemfile. But it goes next new line. In my Gemfile it print like this

```
gem 'pg'
'~> 0.18.1'
```

So I debug the code and found the problem. My gem lines all are like this `gem 'pg'\n\r` by default. Here additionally it has new row(`\r`). So here https://github.com/stompesi/gemput/blob/master/lib/gemput.rb#L57 please add `\r` too for delete the row. Like this 

```
write_text << line.delete!("\n\r") << ", '~> " << gem_version << "'\n"
```

**Comment by stompesi** [comment]
Thank you for advice.
I will fix the bug.

**Comment by stompesi** [comment]
I had to change code like this.

```
write_text << line.sub(/\s+\Z/, "") << ", '~> " << gem_version << "'\n"
```
